stages:
  - lint
  - build
  - test

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint.py --verbose=0 --filter=-whitespace,-line_length include/statistics/welford.h

Compile:
  stage: build
  tags:
    - bfs
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/welford_test

Test Welford:
  stage: test
  tags:
    - bfs
  script:
    - ./build/welford_test