stages:
  - lint
  - build
  - test

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - python cpplint --verbose=5 src/statistics.cc
    - python cpplint --verbose=5 include/statistics.h

Compile:
  stage: build
  tags:
    - bfs
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/welford_test

Test Welford:
  stage: test
  tags:
    - bfs
  script:
    - ./build/welford_test