image: flybrianfly/gcc-cmake

stages:
  - build
  - test

Build code:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

Test code:
  stage: test
  script:
    - make test