

  FROM ubuntu:latest
  
  # Install basic build tools
  RUN apt-get update \
      && apt-get upgrade -y \
      && apt-get install -y git \
      && apt-get install -y build-essential \
      && apt-get install -y cmake \
      && apt-get install -y cpplint
